<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <title>Add Json</title>
</head>
<body>
<div class="page-intro">
    <div class="container">

        <form action="json-upload" method="post" enctype="multipart/form-data">
            <div >
                <input   type="file"
                       name="drinks">
                <button   type="submit"
                        class="">Upload
                </button>
            </div>
        </form>

    </div>
</div>
</body>
</html>