<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="test" method="post">
    <label for="nameMeal">Name:</label> <input type="text" name="name" id="namePost">
    <label for="category">category:</label> <input type="text" name="category" id="category">
    <label for="country">Country</label> <input type="text" name="country" id="country">
    <label for="recipe">Recipe:</label> <input type="text" name="recipe" id="recipe">
    <label for="imageUrl">imageUrl:</label> <input type="text" name="imageUrl" id="imageUrl">
    <label for="youtubeLink">youtubeLink:</label> <input type="text" name="youtubeLink" id="youtubeLink">
    <label for="tagsList">tagsList:</label> <input type="text" name="tagsList" id="tagsList">

    <label for="ingredient1">ingredient1:</label> <input type="text" name="ingredient1" id="ingredient1">
    <label for="measure1">measure1:</label> <input type="text" name="measure1" id="measure1">

    <label for="ingredient2">ingredient2:</label> <input type="text" name="ingredient2" id="ingredient2">
    <label for="measure2">measure2:</label> <input type="text" name="measure2" id="measure2">

    <label for="source">source:</label> <input type="text" name="source" id="source">

    <button type="submit">SEND IT</button>
</form>
</body>
</html>