<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="test" method="post">
    <label for="nameMeal">Name:</label> <input type="text" name="name" id="namePost">
    <label for="recipe">Recipe:</label> <input type="text" name="recipe" id="lastNamePost">
    <label for="country">Country</label> <input type="text" name="country" id="birthDatePost">
    <button type="submit">SEND IT</button>
</form>
</body>
</html>